#file provide by Professor Dixon https://github.com/CSUChico-CINS465/CINS465-F20-Examples 
FROM python:3.8.5
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD . /code/
RUN pip install -r requirements.txt
