# Generated by Django 3.1.1 on 2020-09-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_postmodel_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='header',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
