# Generated by Django 3.1.1 on 2020-12-09 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20201209_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksmodel',
            name='pitcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TrackedStocksModel',
        ),
    ]
