# Generated by Django 3.1.1 on 2020-10-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200929_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='vote',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='DownVote',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='UpVote',
            field=models.IntegerField(default=1),
        ),
    ]
