# Generated by Django 3.1.1 on 2020-10-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201003_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='DownVote',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='UpVote',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='downVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='upVote',
            field=models.IntegerField(default=0),
        ),
    ]
