# Generated by Django 3.1.1 on 2020-10-05 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201005_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='downVote',
            new_name='downVotes',
        ),
        migrations.RenameField(
            model_name='postmodel',
            old_name='upVote',
            new_name='upVotes',
        ),
    ]
