# Generated by Django 3.1.1 on 2020-10-12 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0010_downvotemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='cost',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CatcherModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funds', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
