# Generated by Django 3.1.1 on 2020-10-18 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0011_auto_20201012_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchermodel',
            name='funds',
            field=models.PositiveIntegerField(default=0, verbose_name='Add amount'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='cost',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PurchaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_post', to='myapp.postmodel')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
