# Generated by Django 3.1.2 on 2020-10-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201012_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchermodel',
            name='funds',
            field=models.PositiveIntegerField(default=0, verbose_name='Add amount'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='cost',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
