# Generated by Django 3.1.2 on 2020-10-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201017_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(max_length=1000),
        ),
    ]
