# Generated by Django 3.1.2 on 2020-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20201017_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.CharField(max_length=5000),
        ),
    ]
