# Generated by Django 3.1.2 on 2020-10-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201017_1511'),
        ('myapp', '0012_auto_20201018_0004'),
    ]

    operations = [
    ]
