# Generated by Django 3.1.2 on 2020-11-25 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0017_subscribemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostModel',
            new_name='UserModel',
        ),
    ]
