# Generated by Django 3.1.2 on 2020-11-26 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0019_stocksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedStocksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('category', models.CharField(choices=[(0, 'BUY'), (1, 'HOLD'), (2, 'SELL')], default=1, max_length=4)),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='comparisonGruvest',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='comparisonSP500',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='userFeedback',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=1),
        ),
        migrations.DeleteModel(
            name='StocksModel',
        ),
    ]
