# Generated by Django 3.1.2 on 2020-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_auto_20201127_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksmodel',
            name='name',
        ),
    ]
